### ISSUE TITLE
Hangs on open with MacOS Big Sur (11.2.3)

### ISSUE THREAD

**Issue by iansoper** [mmatyas/pegasus-metadata-editor#11]
When I try to open the app on MacOS Big Sur it just hangs and will show as "Not Responding". 

I think it has to do with QT not being fully compatible with Big Sur.

**Comment by estefan3112** [comment]
Same hang in macOS 12.1 Monterey in Apple Silicon - what the report says (excerpt only):

Command:          pegasus-metaed
Path:             /private/var/folders/*/Pegasus Metadata Editor.app/Contents/MacOS/pegasus-metaed
Identifier:       org.pegasus-frontend.metaed.macos
Architecture:     x86_64 (translated)
Parent:           launchd [1]
PID:              3579
Time Since Fork:  131s

Event:            hang
Duration:         127.20s
Duration Sampled: 1.10s (process was unresponsive for 126 seconds before sampling)
Steps:            11 (100ms sampling interval)

**Comment by estefan3112** [comment]
Edit: building of the source with make just worked!

**Comment by mmatyas** [comment]
I've uploaded a new Mac build to the [releases](https://github.com/mmatyas/pegasus-metadata-editor/releases/tag/continuous), could you try it?

**Comment by estefan3112** [comment]
Works for me now in macOS 12.1 on M1. Thanks!

**Comment by mmatyas** [comment]
I guess this got fixed then.
